export const THIRTYSECOND_CONTENT_REQ = 'THIRTYSECOND_CONTENT_REQ'
export const THIRTYSECOND_CONTENT_SUCCESS = 'THIRTYSECOND_CONTENT_SUCCESS'
export const THIRTYSECOND_CONTENT_FAIL = 'THIRTYSECOND_CONTENT_FAIL'
export const LOADING_FALSE = 'LOADING_FALSE'
