export const SPEAKERS_CONTENT_REQ = 'SPEAKERS_CONTENT_REQ'
export const SPEAKERS_CONTENT_SUCCESS = 'SPEAKERS_CONTENT_SUCCESS'
export const SPEAKERS_CONTENT_FAIL = 'SPEAKERS_CONTENT_FAIL'
export const LOADING_FALSE = 'LOADING_FALSE'
